# Generated by Django 5.1.2 on 2024-11-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=10, verbose_name='Stock Mínimo'),
        ),
    ]
