# Generated by Django 5.1.2 on 2024-11-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
